# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[28,)" #mandatory (26 is current forge version)
# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/TUMods/TU_Adventurecraft_1-14-4/issues" #optional
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
# The modid of the mod
modId="tuadventurecraft" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="0.1.0" #mandatory
 # A display name for the mod
displayName="TU Adventurecraft" #mandatory
# A URL to query for updates for this mod. See the JSON update specification <here>
#updateJSONURL="http://myurl.me/" #optional
# A URL for the "homepage" for this mod, displayed in the mod UI
displayURL="https://www.curseforge.com/minecraft/mc-mods/tu-adventurecraft" #optional
# A file name (in the root of the mod JAR) containing a logo for display
logoFile="TUMods.png" #optional
# A text field displayed in the mod UI
#credits="" #optional
# A text field displayed in the mod UI
authors="Intrepid249, MrUffle" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Adventurecraft is a mod that aims to rehaul and enhance the vanilla experience.
The mod is geared around adding realistic progressions and procedures with crafting and mining, as well as adding a new layer of fantasy with magic and intrigue.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.tuadventurecraft]] #optional
    modId="forge" # the modid of the dependency MANDITORY
    mandatory=true # Does this dependency have to exist - if not, ordering below must be specified MANDITORY
    versionRange="[28,)" # The version range of the dependency MANDITORY
    ordering="NONE" # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    side="BOTH" # Side this dependency is applied on - BOTH, CLIENT or SERVER
